[workspace]
resolver = "2"
members = [
  "crates/g",
  "crates/g-core",
  "crates/g-cpu",
  "crates/g-ad",
  "crates/g-nn",
  "crates/g-apple",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.85"

[workspace.dependencies]
g-core = { path = "crates/g-core" }
g-cpu = { path = "crates/g-cpu" }
g-ad = { path = "crates/g-ad" }
g-nn = { path = "crates/g-nn" }
g-apple = { path = "crates/g-apple" }
