[package]
name = "g-ad"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[features]
default = []
gpu = ["dep:g-apple"]

[dependencies]
g-core.workspace = true
g-cpu.workspace = true
g-apple = { workspace = true, optional = true }
