[package]
name = "g-ad"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
rust-version.workspace = true
description = "Autodiff engine for the g tensor library"
repository = "https://github.com/9nunya/g-tensor"

[features]
default = []
gpu = ["dep:g-apple"]

[dependencies]
g-core.workspace = true
g-cpu.workspace = true
g-apple = { workspace = true, optional = true }
