[package]
name = "g-cpu"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = true
rust-version.workspace = true
description = "CPU kernels and ops for the g tensor library"
repository = "https://github.com/9nunya/G"

[features]
default = ["accelerate"]
accelerate = []

[dependencies]
g-core.workspace = true
rayon = "1.10"
